import Head from 'next/head';
import { useState, useEffect } from 'react';
import Header from '../components/Header';
import Banner from '../components/Banner';
import Body from '../components/Body';
import Popup from '../components/popupForm';
import PopUpSignIn from '../components/PopUpSignIn';
import Posts from '../components/Posts';
import Post from '../components/Post';
export default function Home() {
  const [timedPopup, setTimedPopup] = useState(false);

  useEffect(() => {
    setTimeout(() => {
      setTimedPopup(true);
    }, 3000);
  }, []);
  return (
    <div>
      <Head>
        <title>Figma | UI</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <Popup trigger={timedPopup} setTrigger={setTimedPopup}>
          <PopUpSignIn trigger={timedPopup} setTrigger={setTimedPopup} />
        </Popup>
        <Header />
        <Banner />
        <div className='container'>
          <Body />
          <Posts />
          <Post />
        </div>
      </main>

      <footer></footer>
    </div>
  );
}
